<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use App\Models\State;
use Illuminate\Database\Seeder;

class GeoSeeder extends Seeder
{
    public function run(): void
    {
        // [name, iso2, iso3, phone_code, currency, currency_symbol, emoji]
        $countries = [
            ['Afghanistan', 'AF', 'AFG', '+93', 'AFN', '؋', '🇦🇫'],
            ['Albania', 'AL', 'ALB', '+355', 'ALL', 'L', '🇦🇱'],
            ['Algeria', 'DZ', 'DZA', '+213', 'DZD', 'دج', '🇩🇿'],
            ['Andorra', 'AD', 'AND', '+376', 'EUR', '€', '🇦🇩'],
            ['Angola', 'AO', 'AGO', '+244', 'AOA', 'Kz', '🇦🇴'],
            ['Antigua and Barbuda', 'AG', 'ATG', '+1268', 'XCD', '$', '🇦🇬'],
            ['Argentina', 'AR', 'ARG', '+54', 'ARS', '$', '🇦🇷'],
            ['Armenia', 'AM', 'ARM', '+374', 'AMD', '֏', '🇦🇲'],
            ['Australia', 'AU', 'AUS', '+61', 'AUD', '$', '🇦🇺'],
            ['Austria', 'AT', 'AUT', '+43', 'EUR', '€', '🇦🇹'],
            ['Azerbaijan', 'AZ', 'AZE', '+994', 'AZN', '₼', '🇦🇿'],
            ['Bahamas', 'BS', 'BHS', '+1242', 'BSD', '$', '🇧🇸'],
            ['Bahrain', 'BH', 'BHR', '+973', 'BHD', 'د.ب', '🇧🇭'],
            ['Bangladesh', 'BD', 'BGD', '+880', 'BDT', '৳', '🇧🇩'],
            ['Barbados', 'BB', 'BRB', '+1246', 'BBD', '$', '🇧🇧'],
            ['Belarus', 'BY', 'BLR', '+375', 'BYN', 'Br', '🇧🇾'],
            ['Belgium', 'BE', 'BEL', '+32', 'EUR', '€', '🇧🇪'],
            ['Belize', 'BZ', 'BLZ', '+501', 'BZD', '$', '🇧🇿'],
            ['Benin', 'BJ', 'BEN', '+229', 'XOF', null, '🇧🇯'],
            ['Bhutan', 'BT', 'BTN', '+975', 'BTN', 'Nu.', '🇧🇹'],
            ['Bolivia', 'BO', 'BOL', '+591', 'BOB', 'Bs.', '🇧🇴'],
            ['Bosnia and Herzegovina', 'BA', 'BIH', '+387', 'BAM', 'KM', '🇧🇦'],
            ['Botswana', 'BW', 'BWA', '+267', 'BWP', 'P', '🇧🇼'],
            ['Brazil', 'BR', 'BRA', '+55', 'BRL', 'R$', '🇧🇷'],
            ['Brunei', 'BN', 'BRN', '+673', 'BND', '$', '🇧🇳'],
            ['Bulgaria', 'BG', 'BGR', '+359', 'BGN', 'лв', '🇧🇬'],
            ['Burkina Faso', 'BF', 'BFA', '+226', 'XOF', null, '🇧🇫'],
            ['Burundi', 'BI', 'BDI', '+257', 'BIF', 'FBu', '🇧🇮'],
            ['Cambodia', 'KH', 'KHM', '+855', 'KHR', '៛', '🇰🇭'],
            ['Cameroon', 'CM', 'CMR', '+237', 'XAF', 'FCFA', '🇨🇲'],
            ['Canada', 'CA', 'CAN', '+1', 'CAD', '$', '🇨🇦'],
            ['Cape Verde', 'CV', 'CPV', '+238', 'CVE', '$', '🇨🇻'],
            ['Central African Republic', 'CF', 'CAF', '+236', 'XAF', 'FCFA', '🇨🇫'],
            ['Chad', 'TD', 'TCD', '+235', 'XAF', 'FCFA', '🇹🇩'],
            ['Chile', 'CL', 'CHL', '+56', 'CLP', '$', '🇨🇱'],
            ['China', 'CN', 'CHN', '+86', 'CNY', '¥', '🇨🇳'],
            ['Colombia', 'CO', 'COL', '+57', 'COP', '$', '🇨🇴'],
            ['Comoros', 'KM', 'COM', '+269', 'KMF', 'CF', '🇰🇲'],
            ['Congo (Republic of the)', 'CG', 'COG', '+242', 'XAF', 'FCFA', '🇨🇬'],
            ['Congo (Democratic Republic of the)', 'CD', 'COD', '+243', 'CDF', 'FC', '🇨🇩'],
            ['Costa Rica', 'CR', 'CRI', '+506', 'CRC', '₡', '🇨🇷'],
            ['Croatia', 'HR', 'HRV', '+385', 'EUR', '€', '🇭🇷'],
            ['Cuba', 'CU', 'CUB', '+53', 'CUP', '$', '🇨🇺'],
            ['Cyprus', 'CY', 'CYP', '+357', 'EUR', '€', '🇨🇾'],
            ['Czech Republic', 'CZ', 'CZE', '+420', 'CZK', 'Kč', '🇨🇿'],
            ['Denmark', 'DK', 'DNK', '+45', 'DKK', 'kr', '🇩🇰'],
            ['Djibouti', 'DJ', 'DJI', '+253', 'DJF', 'Fdj', '🇩🇯'],
            ['Dominica', 'DM', 'DMA', '+1767', 'XCD', '$', '🇩🇲'],
            ['Dominican Republic', 'DO', 'DOM', '+1809', 'DOP', 'RD$', '🇩🇴'],
            ['Ecuador', 'EC', 'ECU', '+593', 'USD', '$', '🇪🇨'],
            ['Egypt', 'EG', 'EGY', '+20', 'EGP', '£', '🇪🇬'],
            ['El Salvador', 'SV', 'SLV', '+503', 'USD', '$', '🇸🇻'],
            ['Equatorial Guinea', 'GQ', 'GNQ', '+240', 'XAF', 'FCFA', '🇬🇶'],
            ['Eritrea', 'ER', 'ERI', '+291', 'ERN', 'Nfk', '🇪🇷'],
            ['Estonia', 'EE', 'EST', '+372', 'EUR', '€', '🇪🇪'],
            ['Eswatini', 'SZ', 'SWZ', '+268', 'SZL', 'L', '🇸🇿'],
            ['Ethiopia', 'ET', 'ETH', '+251', 'ETB', 'Br', '🇪🇹'],
            ['Fiji', 'FJ', 'FJI', '+679', 'FJD', '$', '🇫🇯'],
            ['Finland', 'FI', 'FIN', '+358', 'EUR', '€', '🇫🇮'],
            ['France', 'FR', 'FRA', '+33', 'EUR', '€', '🇫🇷'],
            ['Gabon', 'GA', 'GAB', '+241', 'XAF', 'FCFA', '🇬🇦'],
            ['Gambia', 'GM', 'GMB', '+220', 'GMD', 'D', '🇬🇲'],
            ['Georgia', 'GE', 'GEO', '+995', 'GEL', '₾', '🇬🇪'],
            ['Germany', 'DE', 'DEU', '+49', 'EUR', '€', '🇩🇪'],
            ['Ghana', 'GH', 'GHA', '+233', 'GHS', '₵', '🇬🇭'],
            ['Greece', 'GR', 'GRC', '+30', 'EUR', '€', '🇬🇷'],
            ['Grenada', 'GD', 'GRD', '+1473', 'XCD', '$', '🇬🇩'],
            ['Guatemala', 'GT', 'GTM', '+502', 'GTQ', 'Q', '🇬🇹'],
            ['Guinea', 'GN', 'GIN', '+224', 'GNF', 'FG', '🇬🇳'],
            ['Guinea-Bissau', 'GW', 'GNB', '+245', 'XOF', null, '🇬🇼'],
            ['Guyana', 'GY', 'GUY', '+592', 'GYD', '$', '🇬🇾'],
            ['Haiti', 'HT', 'HTI', '+509', 'HTG', 'G', '🇭🇹'],
            ['Honduras', 'HN', 'HND', '+504', 'HNL', 'L', '🇭🇳'],
            ['Hong Kong', 'HK', 'HKG', '+852', 'HKD', 'HK$', '🇭🇰'],
            ['Hungary', 'HU', 'HUN', '+36', 'HUF', 'Ft', '🇭🇺'],
            ['Iceland', 'IS', 'ISL', '+354', 'ISK', 'kr', '🇮🇸'],
            ['India', 'IN', 'IND', '+91', 'INR', '₹', '🇮🇳'],
            ['Indonesia', 'ID', 'IDN', '+62', 'IDR', 'Rp', '🇮🇩'],
            ['Iran', 'IR', 'IRN', '+98', 'IRR', '﷼', '🇮🇷'],
            ['Iraq', 'IQ', 'IRQ', '+964', 'IQD', 'ع.د', '🇮🇶'],
            ['Ireland', 'IE', 'IRL', '+353', 'EUR', '€', '🇮🇪'],
            ['Israel', 'IL', 'ISR', '+972', 'ILS', '₪', '🇮🇱'],
            ['Italy', 'IT', 'ITA', '+39', 'EUR', '€', '🇮🇹'],
            ['Ivory Coast', 'CI', 'CIV', '+225', 'XOF', null, '🇨🇮'],
            ['Jamaica', 'JM', 'JAM', '+1876', 'JMD', '$', '🇯🇲'],
            ['Japan', 'JP', 'JPN', '+81', 'JPY', '¥', '🇯🇵'],
            ['Jordan', 'JO', 'JOR', '+962', 'JOD', 'د.ا', '🇯🇴'],
            ['Kazakhstan', 'KZ', 'KAZ', '+7', 'KZT', '₸', '🇰🇿'],
            ['Kenya', 'KE', 'KEN', '+254', 'KES', 'Sh', '🇰🇪'],
            ['Kiribati', 'KI', 'KIR', '+686', 'AUD', '$', '🇰🇮'],
            ['Kosovo', 'XK', 'XKX', '+383', 'EUR', '€', '🇽🇰'],
            ['Kuwait', 'KW', 'KWT', '+965', 'KWD', 'د.ك', '🇰🇼'],
            ['Kyrgyzstan', 'KG', 'KGZ', '+996', 'KGS', 'som', '🇰🇬'],
            ['Laos', 'LA', 'LAO', '+856', 'LAK', '₭', '🇱🇦'],
            ['Latvia', 'LV', 'LVA', '+371', 'EUR', '€', '🇱🇻'],
            ['Lebanon', 'LB', 'LBN', '+961', 'LBP', 'ل.ل', '🇱🇧'],
            ['Lesotho', 'LS', 'LSO', '+266', 'LSL', 'L', '🇱🇸'],
            ['Liberia', 'LR', 'LBR', '+231', 'LRD', '$', '🇱🇷'],
            ['Libya', 'LY', 'LBY', '+218', 'LYD', 'ل.د', '🇱🇾'],
            ['Liechtenstein', 'LI', 'LIE', '+423', 'CHF', 'Fr', '🇱🇮'],
            ['Lithuania', 'LT', 'LTU', '+370', 'EUR', '€', '🇱🇹'],
            ['Luxembourg', 'LU', 'LUX', '+352', 'EUR', '€', '🇱🇺'],
            ['Macau', 'MO', 'MAC', '+853', 'MOP', 'P', '🇲🇴'],
            ['Madagascar', 'MG', 'MDG', '+261', 'MGA', 'Ar', '🇲🇬'],
            ['Malawi', 'MW', 'MWI', '+265', 'MWK', 'MK', '🇲🇼'],
            ['Malaysia', 'MY', 'MYS', '+60', 'MYR', 'RM', '🇲🇾'],
            ['Maldives', 'MV', 'MDV', '+960', 'MVR', 'Rf', '🇲🇻'],
            ['Mali', 'ML', 'MLI', '+223', 'XOF', null, '🇲🇱'],
            ['Malta', 'MT', 'MLT', '+356', 'EUR', '€', '🇲🇹'],
            ['Marshall Islands', 'MH', 'MHL', '+692', 'USD', '$', '🇲🇭'],
            ['Mauritania', 'MR', 'MRT', '+222', 'MRU', 'UM', '🇲🇷'],
            ['Mauritius', 'MU', 'MUS', '+230', 'MUR', '₨', '🇲🇺'],
            ['Mexico', 'MX', 'MEX', '+52', 'MXN', '$', '🇲🇽'],
            ['Micronesia', 'FM', 'FSM', '+691', 'USD', '$', '🇫🇲'],
            ['Moldova', 'MD', 'MDA', '+373', 'MDL', 'L', '🇲🇩'],
            ['Monaco', 'MC', 'MCO', '+377', 'EUR', '€', '🇲🇨'],
            ['Mongolia', 'MN', 'MNG', '+976', 'MNT', '₮', '🇲🇳'],
            ['Montenegro', 'ME', 'MNE', '+382', 'EUR', '€', '🇲🇪'],
            ['Morocco', 'MA', 'MAR', '+212', 'MAD', 'د.م.', '🇲🇦'],
            ['Mozambique', 'MZ', 'MOZ', '+258', 'MZN', 'MT', '🇲🇿'],
            ['Myanmar', 'MM', 'MMR', '+95', 'MMK', 'Ks', '🇲🇲'],
            ['Namibia', 'NA', 'NAM', '+264', 'NAD', '$', '🇳🇦'],
            ['Nauru', 'NR', 'NRU', '+674', 'AUD', '$', '🇳🇷'],
            ['Nepal', 'NP', 'NPL', '+977', 'NPR', 'Rs', '🇳🇵'],
            ['Netherlands', 'NL', 'NLD', '+31', 'EUR', '€', '🇳🇱'],
            ['New Zealand', 'NZ', 'NZL', '+64', 'NZD', '$', '🇳🇿'],
            ['Nicaragua', 'NI', 'NIC', '+505', 'NIO', 'C$', '🇳🇮'],
            ['Niger', 'NE', 'NER', '+227', 'XOF', null, '🇳🇪'],
            ['Nigeria', 'NG', 'NGA', '+234', 'NGN', '₦', '🇳🇬'],
            ['North Korea', 'KP', 'PRK', '+850', 'KPW', '₩', '🇰🇵'],
            ['North Macedonia', 'MK', 'MKD', '+389', 'MKD', 'ден', '🇲🇰'],
            ['Norway', 'NO', 'NOR', '+47', 'NOK', 'kr', '🇳🇴'],
            ['Oman', 'OM', 'OMN', '+968', 'OMR', 'ر.ع.', '🇴🇲'],
            ['Pakistan', 'PK', 'PAK', '+92', 'PKR', '₨', '🇵🇰'],
            ['Palau', 'PW', 'PLW', '+680', 'USD', '$', '🇵🇼'],
            ['Palestine', 'PS', 'PSE', '+970', 'ILS', '₪', '🇵🇸'],
            ['Panama', 'PA', 'PAN', '+507', 'PAB', 'B/.', '🇵🇦'],
            ['Papua New Guinea', 'PG', 'PNG', '+675', 'PGK', 'K', '🇵🇬'],
            ['Paraguay', 'PY', 'PRY', '+595', 'PYG', '₲', '🇵🇾'],
            ['Peru', 'PE', 'PER', '+51', 'PEN', 'S/', '🇵🇪'],
            ['Philippines', 'PH', 'PHL', '+63', 'PHP', '₱', '🇵🇭'],
            ['Poland', 'PL', 'POL', '+48', 'PLN', 'zł', '🇵🇱'],
            ['Portugal', 'PT', 'PRT', '+351', 'EUR', '€', '🇵🇹'],
            ['Qatar', 'QA', 'QAT', '+974', 'QAR', 'ر.ق', '🇶🇦'],
            ['Romania', 'RO', 'ROU', '+40', 'RON', 'lei', '🇷🇴'],
            ['Russia', 'RU', 'RUS', '+7', 'RUB', '₽', '🇷🇺'],
            ['Rwanda', 'RW', 'RWA', '+250', 'RWF', 'FRw', '🇷🇼'],
            ['Saint Kitts and Nevis', 'KN', 'KNA', '+1869', 'XCD', '$', '🇰🇳'],
            ['Saint Lucia', 'LC', 'LCA', '+1758', 'XCD', '$', '🇱🇨'],
            ['Saint Vincent and the Grenadines', 'VC', 'VCT', '+1784', 'XCD', '$', '🇻🇨'],
            ['Samoa', 'WS', 'WSM', '+685', 'WST', 'T', '🇼🇸'],
            ['San Marino', 'SM', 'SMR', '+378', 'EUR', '€', '🇸🇲'],
            ['Sao Tome and Principe', 'ST', 'STP', '+239', 'STN', 'Db', '🇸🇹'],
            ['Saudi Arabia', 'SA', 'SAU', '+966', 'SAR', '﷼', '🇸🇦'],
            ['Senegal', 'SN', 'SEN', '+221', 'XOF', null, '🇸🇳'],
            ['Serbia', 'RS', 'SRB', '+381', 'RSD', 'дин', '🇷🇸'],
            ['Seychelles', 'SC', 'SYC', '+248', 'SCR', '₨', '🇸🇨'],
            ['Sierra Leone', 'SL', 'SLE', '+232', 'SLL', 'Le', '🇸🇱'],
            ['Singapore', 'SG', 'SGP', '+65', 'SGD', '$', '🇸🇬'],
            ['Slovakia', 'SK', 'SVK', '+421', 'EUR', '€', '🇸🇰'],
            ['Slovenia', 'SI', 'SVN', '+386', 'EUR', '€', '🇸🇮'],
            ['Solomon Islands', 'SB', 'SLB', '+677', 'SBD', '$', '🇸🇧'],
            ['Somalia', 'SO', 'SOM', '+252', 'SOS', 'Sh', '🇸🇴'],
            ['South Africa', 'ZA', 'ZAF', '+27', 'ZAR', 'R', '🇿🇦'],
            ['South Korea', 'KR', 'KOR', '+82', 'KRW', '₩', '🇰🇷'],
            ['South Sudan', 'SS', 'SSD', '+211', 'SSP', '£', '🇸🇸'],
            ['Spain', 'ES', 'ESP', '+34', 'EUR', '€', '🇪🇸'],
            ['Sri Lanka', 'LK', 'LKA', '+94', 'LKR', 'Rs', '🇱🇰'],
            ['Sudan', 'SD', 'SDN', '+249', 'SDG', '£', '🇸🇩'],
            ['Suriname', 'SR', 'SUR', '+597', 'SRD', '$', '🇸🇷'],
            ['Sweden', 'SE', 'SWE', '+46', 'SEK', 'kr', '🇸🇪'],
            ['Switzerland', 'CH', 'CHE', '+41', 'CHF', 'Fr', '🇨🇭'],
            ['Syria', 'SY', 'SYR', '+963', 'SYP', '£', '🇸🇾'],
            ['Taiwan', 'TW', 'TWN', '+886', 'TWD', 'NT$', '🇹🇼'],
            ['Tajikistan', 'TJ', 'TJK', '+992', 'TJS', 'SM', '🇹🇯'],
            ['Tanzania', 'TZ', 'TZA', '+255', 'TZS', 'Sh', '🇹🇿'],
            ['Thailand', 'TH', 'THA', '+66', 'THB', '฿', '🇹🇭'],
            ['Timor-Leste', 'TL', 'TLS', '+670', 'USD', '$', '🇹🇱'],
            ['Togo', 'TG', 'TGO', '+228', 'XOF', null, '🇹🇬'],
            ['Tonga', 'TO', 'TON', '+676', 'TOP', 'T$', '🇹🇴'],
            ['Trinidad and Tobago', 'TT', 'TTO', '+1868', 'TTD', 'TT$', '🇹🇹'],
            ['Tunisia', 'TN', 'TUN', '+216', 'TND', 'د.ت', '🇹🇳'],
            ['Turkey', 'TR', 'TUR', '+90', 'TRY', '₺', '🇹🇷'],
            ['Turkmenistan', 'TM', 'TKM', '+993', 'TMT', 'm', '🇹🇲'],
            ['Tuvalu', 'TV', 'TUV', '+688', 'AUD', '$', '🇹🇻'],
            ['Uganda', 'UG', 'UGA', '+256', 'UGX', 'USh', '🇺🇬'],
            ['Ukraine', 'UA', 'UKR', '+380', 'UAH', '₴', '🇺🇦'],
            ['United Arab Emirates', 'AE', 'ARE', '+971', 'AED', 'د.إ', '🇦🇪'],
            ['United Kingdom', 'GB', 'GBR', '+44', 'GBP', '£', '🇬🇧'],
            ['United States', 'US', 'USA', '+1', 'USD', '$', '🇺🇸'],
            ['Uruguay', 'UY', 'URY', '+598', 'UYU', '$', '🇺🇾'],
            ['Uzbekistan', 'UZ', 'UZB', '+998', 'UZS', 'soʻm', '🇺🇿'],
            ['Vanuatu', 'VU', 'VUT', '+678', 'VUV', 'Vt', '🇻🇺'],
            ['Vatican City', 'VA', 'VAT', '+379', 'EUR', '€', '🇻🇦'],
            ['Venezuela', 'VE', 'VEN', '+58', 'VES', 'Bs.', '🇻🇪'],
            ['Vietnam', 'VN', 'VNM', '+84', 'VND', '₫', '🇻🇳'],
            ['Yemen', 'YE', 'YEM', '+967', 'YER', '﷼', '🇾🇪'],
            ['Zambia', 'ZM', 'ZMB', '+260', 'ZMW', 'K', '🇿🇲'],
            ['Zimbabwe', 'ZW', 'ZWE', '+263', 'ZWL', '$', '🇿🇼'],
        ];

        foreach ($countries as $row) {
            Country::updateOrCreate(['iso2' => $row[1]], [
                'name'            => $row[0],
                'iso3'            => $row[2],
                'phone_code'      => $row[3],
                'currency'        => $row[4],
                'currency_symbol' => $row[5],
                'emoji'           => $row[6],
                'status'          => true,
            ]);
        }

        $countryIds = Country::pluck('id', 'iso2');

        // iso2 => [state name, state code, [cities...]]
        $locations = [
            'IN' => [
                ['Andhra Pradesh', 'AP', ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool', 'Rajahmundry', 'Kakinada', 'Tirupati', 'Anantapur', 'Kadapa', 'Eluru']],
                ['Arunachal Pradesh', 'AR', ['Itanagar', 'Naharlagun', 'Pasighat']],
                ['Assam', 'AS', ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon', 'Tezpur', 'Tinsukia']],
                ['Bihar', 'BR', ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga', 'Purnia', 'Arrah', 'Begusarai', 'Katihar']],
                ['Chhattisgarh', 'CG', ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Raigarh']],
                ['Goa', 'GA', ['Panaji', 'Vasco da Gama', 'Mapusa', 'Margao', 'Ponda']],
                ['Gujarat', 'GJ', ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Junagadh', 'Gandhinagar', 'Gandhidham', 'Anand', 'Morbi', 'Nadiad', 'Mehsana']],
                ['Haryana', 'HR', ['Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Yamunanagar', 'Rohtak', 'Hisar', 'Karnal', 'Sonipat']],
                ['Himachal Pradesh', 'HP', ['Shimla', 'Dharamshala', 'Manali', 'Solan', 'Mandi', 'Baddi']],
                ['Jharkhand', 'JH', ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar', 'Hazaribagh']],
                ['Karnataka', 'KA', ['Bengaluru', 'Mysuru', 'Hubballi-Dharwad', 'Kalaburagi', 'Mangaluru', 'Belagavi', 'Davanagere', 'Ballari', 'Vijayapura', 'Shivamogga', 'Tumakuru', 'Udupi']],
                ['Kerala', 'KL', ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Kollam', 'Kannur', 'Alappuzha', 'Palakkad', 'Kottayam', 'Malappuram']],
                ['Madhya Pradesh', 'MP', ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Ujjain', 'Sagar', 'Dewas', 'Satna', 'Ratlam', 'Rewa', 'Burhanpur']],
                ['Maharashtra', 'MH', ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Thane', 'Aurangabad', 'Solapur', 'Kolhapur', 'Amravati', 'Navi Mumbai', 'Kalyan-Dombivli', 'Vasai-Virar', 'Bhiwandi', 'Malegaon', 'Akola', 'Jalgaon', 'Latur', 'Dhule', 'Ahmednagar', 'Chandrapur', 'Parbhani', 'Sangli']],
                ['Manipur', 'MN', ['Imphal', 'Thoubal', 'Bishnupur']],
                ['Meghalaya', 'ML', ['Shillong', 'Tura', 'Jowai']],
                ['Mizoram', 'MZ', ['Aizawl', 'Lunglei', 'Champhai']],
                ['Nagaland', 'NL', ['Kohima', 'Dimapur', 'Mokokchung']],
                ['Odisha', 'OD', ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur', 'Puri', 'Balasore']],
                ['Punjab', 'PB', ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Hoshiarpur', 'Mohali', 'Pathankot']],
                ['Rajasthan', 'RJ', ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner', 'Ajmer', 'Bharatpur', 'Alwar', 'Sikar', 'Bhilwara', 'Sri Ganganagar']],
                ['Sikkim', 'SK', ['Gangtok', 'Namchi', 'Gyalshing']],
                ['Tamil Nadu', 'TN', ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 'Tiruppur', 'Tirunelveli', 'Vellore', 'Erode', 'Thoothukudi', 'Dindigul', 'Thanjavur', 'Cuddalore', 'Nagercoil', 'Hosur', 'Udhagamandalam', 'Kanyakumari']],
                ['Telangana', 'TS', ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam', 'Ramagundam', 'Mahbubnagar', 'Adilabad', 'Siddipet']],
                ['Tripura', 'TR', ['Agartala', 'Udaipur', 'Dharmanagar']],
                ['Uttar Pradesh', 'UP', ['Lucknow', 'Kanpur', 'Ghaziabad', 'Agra', 'Varanasi', 'Meerut', 'Prayagraj', 'Bareilly', 'Aligarh', 'Moradabad', 'Saharanpur', 'Gorakhpur', 'Noida', 'Greater Noida', 'Farrukhabad', 'Jhansi', 'Mathura', 'Ayodhya', 'Rampur', 'Shahjahanpur', 'Firozabad']],
                ['Uttarakhand', 'UK', ['Dehradun', 'Haridwar', 'Rishikesh', 'Nainital', 'Roorkee', 'Haldwani']],
                ['West Bengal', 'WB', ['Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri', 'Bardhaman', 'Kharagpur', 'Haldia', 'Darjeeling', 'Malda', 'Murshidabad']],
                ['Andaman and Nicobar Islands', 'AN', ['Port Blair']],
                ['Chandigarh', 'CH', ['Chandigarh']],
                ['Dadra and Nagar Haveli and Daman and Diu', 'DH', ['Daman', 'Diu', 'Silvassa']],
                ['Delhi', 'DL', ['New Delhi', 'Dwarka', 'Rohini', 'Lajpat Nagar', 'Saket']],
                ['Jammu and Kashmir', 'JK', ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Udhampur']],
                ['Ladakh', 'LA', ['Leh', 'Kargil']],
                ['Lakshadweep', 'LD', ['Kavaratti', 'Minicoy']],
                ['Puducherry', 'PY', ['Puducherry', 'Karaikal', 'Mahe']],
            ],
            'US' => [
                ['Alabama', 'AL', ['Birmingham', 'Montgomery', 'Mobile']],
                ['Alaska', 'AK', ['Anchorage', 'Juneau', 'Fairbanks']],
                ['Arizona', 'AZ', ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale']],
                ['Arkansas', 'AR', ['Little Rock', 'Fayetteville']],
                ['California', 'CA', ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento', 'Oakland', 'Fresno', 'Long Beach']],
                ['Colorado', 'CO', ['Denver', 'Colorado Springs', 'Boulder']],
                ['Connecticut', 'CT', ['Bridgeport', 'Hartford', 'New Haven']],
                ['Delaware', 'DE', ['Wilmington', 'Dover']],
                ['District of Columbia', 'DC', ['Washington']],
                ['Florida', 'FL', ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Fort Lauderdale', 'Tallahassee', 'Gainesville']],
                ['Georgia', 'GA', ['Atlanta', 'Savannah', 'Augusta']],
                ['Hawaii', 'HI', ['Honolulu', 'Hilo']],
                ['Idaho', 'ID', ['Boise', 'Nampa']],
                ['Illinois', 'IL', ['Chicago', 'Naperville', 'Peoria', 'Springfield']],
                ['Indiana', 'IN', ['Indianapolis', 'Fort Wayne', 'Evansville']],
                ['Iowa', 'IA', ['Des Moines', 'Cedar Rapids']],
                ['Kansas', 'KS', ['Wichita', 'Kansas City', 'Topeka']],
                ['Kentucky', 'KY', ['Louisville', 'Lexington']],
                ['Louisiana', 'LA', ['New Orleans', 'Baton Rouge', 'Shreveport']],
                ['Maine', 'ME', ['Portland', 'Augusta']],
                ['Maryland', 'MD', ['Baltimore', 'Annapolis', 'Rockville']],
                ['Massachusetts', 'MA', ['Boston', 'Cambridge', 'Worcester', 'Springfield']],
                ['Michigan', 'MI', ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing']],
                ['Minnesota', 'MN', ['Minneapolis', 'Saint Paul', 'Rochester']],
                ['Mississippi', 'MS', ['Jackson', 'Gulfport']],
                ['Missouri', 'MO', ['Kansas City', 'Saint Louis', 'Springfield']],
                ['Montana', 'MT', ['Billings', 'Missoula']],
                ['Nebraska', 'NE', ['Omaha', 'Lincoln']],
                ['Nevada', 'NV', ['Las Vegas', 'Reno', 'Henderson']],
                ['New Hampshire', 'NH', ['Manchester', 'Concord']],
                ['New Jersey', 'NJ', ['Newark', 'Jersey City', 'Paterson', 'Trenton']],
                ['New Mexico', 'NM', ['Albuquerque', 'Santa Fe']],
                ['New York', 'NY', ['New York City', 'Buffalo', 'Rochester', 'Albany', 'Syracuse', 'Yonkers']],
                ['North Carolina', 'NC', ['Charlotte', 'Raleigh', 'Greensboro', 'Durham']],
                ['North Dakota', 'ND', ['Fargo', 'Bismarck']],
                ['Ohio', 'OH', ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Dayton']],
                ['Oklahoma', 'OK', ['Oklahoma City', 'Tulsa']],
                ['Oregon', 'OR', ['Portland', 'Salem', 'Eugene']],
                ['Pennsylvania', 'PA', ['Philadelphia', 'Pittsburgh', 'Allentown', 'Harrisburg']],
                ['Rhode Island', 'RI', ['Providence', 'Warwick']],
                ['South Carolina', 'SC', ['Charleston', 'Columbia', 'Greenville']],
                ['South Dakota', 'SD', ['Sioux Falls', 'Rapid City']],
                ['Tennessee', 'TN', ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga']],
                ['Texas', 'TX', ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'El Paso', 'Plano', 'Corpus Christi']],
                ['Utah', 'UT', ['Salt Lake City', 'Provo', 'West Valley City']],
                ['Vermont', 'VT', ['Burlington', 'Montpelier']],
                ['Virginia', 'VA', ['Virginia Beach', 'Norfolk', 'Richmond', 'Alexandria']],
                ['Washington', 'WA', ['Seattle', 'Spokane', 'Tacoma', 'Bellevue']],
                ['West Virginia', 'WV', ['Charleston', 'Huntington']],
                ['Wisconsin', 'WI', ['Milwaukee', 'Madison', 'Green Bay']],
                ['Wyoming', 'WY', ['Cheyenne', 'Casper']],
            ],
            'GB' => [
                ['England', 'ENG', ['London', 'Manchester', 'Birmingham', 'Leeds', 'Liverpool', 'Newcastle', 'Bristol', 'Sheffield', 'Nottingham', 'Brighton', 'Leicester', 'Southampton', 'Oxford', 'Cambridge']],
                ['Northern Ireland', 'NIR', ['Belfast', 'Derry', 'Newry']],
                ['Scotland', 'SCT', ['Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee', 'Inverness']],
                ['Wales', 'WLS', ['Cardiff', 'Swansea', 'Newport', 'Bangor']],
            ],
            'CA' => [
                ['Alberta', 'AB', ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge']],
                ['British Columbia', 'BC', ['Vancouver', 'Victoria', 'Kelowna', 'Surrey', 'Burnaby']],
                ['Manitoba', 'MB', ['Winnipeg', 'Brandon']],
                ['New Brunswick', 'NB', ['Moncton', 'Saint John', 'Fredericton']],
                ['Newfoundland and Labrador', 'NL', ['St. John\'s', 'Corner Brook']],
                ['Northwest Territories', 'NT', ['Yellowknife']],
                ['Nova Scotia', 'NS', ['Halifax', 'Sydney', 'Dartmouth']],
                ['Nunavut', 'NU', ['Iqaluit']],
                ['Ontario', 'ON', ['Toronto', 'Ottawa', 'Mississauga', 'Brampton', 'Hamilton', 'London', 'Kitchener', 'Windsor', 'Thunder Bay']],
                ['Prince Edward Island', 'PE', ['Charlottetown', 'Summerside']],
                ['Quebec', 'QC', ['Montreal', 'Quebec City', 'Laval', 'Gatineau', 'Sherbrooke', 'Saguenay']],
                ['Saskatchewan', 'SK', ['Saskatoon', 'Regina']],
                ['Yukon', 'YT', ['Whitehorse']],
            ],
            'AU' => [
                ['Australian Capital Territory', 'ACT', ['Canberra']],
                ['New South Wales', 'NSW', ['Sydney', 'Newcastle', 'Wollongong', 'Central Coast']],
                ['Northern Territory', 'NT', ['Darwin', 'Alice Springs']],
                ['Queensland', 'QLD', ['Brisbane', 'Gold Coast', 'Cairns', 'Townsville', 'Sunshine Coast']],
                ['South Australia', 'SA', ['Adelaide']],
                ['Tasmania', 'TAS', ['Hobart', 'Launceston']],
                ['Victoria', 'VIC', ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo']],
                ['Western Australia', 'WA', ['Perth', 'Bunbury']],
            ],
            'AE' => [
                ['Abu Dhabi', 'AZ', ['Abu Dhabi', 'Al Ain']],
                ['Dubai', 'DU', ['Dubai']],
                ['Sharjah', 'SH', ['Sharjah', 'Khor Fakkan']],
                ['Ajman', 'AJ', ['Ajman']],
                ['Ras Al Khaimah', 'RK', ['Ras Al Khaimah']],
                ['Fujairah', 'FU', ['Fujairah']],
                ['Umm Al Quwain', 'UQ', ['Umm Al Quwain']],
            ],
            'SA' => [
                ['Riyadh', '01', ['Riyadh']],
                ['Makkah', '02', ['Makkah', 'Jeddah', 'Taif']],
                ['Medina', '03', ['Medina']],
                ['Eastern Province', '04', ['Dammam', 'Khobar', 'Dhahran', 'Jubail']],
                ['Asir', '14', ['Abha', 'Khamis Mushait']],
                ['Qassim', '05', ['Buraidah']],
                ['Tabuk', '07', ['Tabuk']],
                ['Jazan', '09', ['Jazan']],
            ],
            'PK' => [
                ['Punjab', 'PB', ['Lahore', 'Faisalabad', 'Rawalpindi', 'Multan', 'Gujranwala', 'Sialkot', 'Bahawalpur']],
                ['Sindh', 'SD', ['Karachi', 'Hyderabad', 'Sukkur', 'Larkana']],
                ['Khyber Pakhtunkhwa', 'KP', ['Peshawar', 'Mardan', 'Abbottabad', 'Swat']],
                ['Balochistan', 'BA', ['Quetta']],
                ['Islamabad', 'IS', ['Islamabad']],
            ],
            'BD' => [
                ['Dhaka', '03', ['Dhaka', 'Narayanganj', 'Gazipur']],
                ['Chattogram', '05', ['Chattogram', 'Comilla']],
                ['Khulna', '07', ['Khulna']],
                ['Rajshahi', '08', ['Rajshahi']],
                ['Sylhet', '06', ['Sylhet']],
                ['Barishal', '04', ['Barishal']],
                ['Rangpur', '09', ['Rangpur']],
                ['Mymensingh', '10', ['Mymensingh']],
            ],
            'LK' => [
                ['Western', '1', ['Colombo', 'Gampaha', 'Negombo']],
                ['Central', '2', ['Kandy', 'Nuwara Eliya']],
                ['Southern', '3', ['Galle', 'Matara']],
                ['Northern', '4', ['Jaffna']],
                ['Eastern', '5', ['Trincomalee', 'Batticaloa']],
                ['North Western', '6', ['Kurunegala']],
                ['North Central', '7', ['Anuradhapura']],
                ['Uva', '8', ['Badulla']],
                ['Sabaragamuwa', '9', ['Ratnapura']],
            ],
            'NP' => [
                ['Bagmati', 'BA', ['Kathmandu', 'Lalitpur']],
                ['Koshi', 'KO', ['Biratnagar']],
                ['Gandaki', 'GA', ['Pokhara']],
                ['Lumbini', 'LU', ['Butwal']],
                ['Madhesh', 'MA', ['Janakpur']],
                ['Karnali', 'KA', ['Nepalgunj']],
                ['Sudurpashchim', 'SU', ['Dhangadhi']],
            ],
            'MY' => [
                ['Kuala Lumpur', '14', ['Kuala Lumpur']],
                ['Selangor', '12', ['Shah Alam', 'Petaling Jaya', 'Subang Jaya']],
                ['Johor', '01', ['Johor Bahru']],
                ['Penang', '07', ['George Town', 'Bukit Mertajam']],
                ['Sarawak', '13', ['Kuching', 'Miri']],
                ['Sabah', '04', ['Kota Kinabalu']],
                ['Melaka', '04', ['Malacca City']],
                ['Pahang', '06', ['Kuantan']],
            ],
            'ID' => [
                ['Jakarta', 'JK', ['Jakarta']],
                ['West Java', 'JB', ['Bandung', 'Bogor', 'Bekasi', 'Depok']],
                ['Central Java', 'JT', ['Semarang', 'Surakarta']],
                ['East Java', 'JI', ['Surabaya', 'Malang', 'Kediri']],
                ['Banten', 'BT', ['Tangerang', 'Serang']],
                ['North Sumatra', 'SU', ['Medan']],
                ['Bali', 'BA', ['Denpasar']],
                ['Yogyakarta', 'YO', ['Yogyakarta']],
                ['South Sulawesi', 'SN', ['Makassar']],
            ],
            'TH' => [
                ['Bangkok', '10', ['Bangkok']],
                ['Chiang Mai', '50', ['Chiang Mai']],
                ['Phuket', '83', ['Phuket']],
                ['Chonburi', '20', ['Pattaya', 'Chonburi']],
                ['Songkhla', '90', ['Hat Yai', 'Songkhla']],
                ['Nakhon Ratchasima', '30', ['Nakhon Ratchasima']],
            ],
            'VN' => [
                ['Hanoi', 'HN', ['Hanoi']],
                ['Ho Chi Minh City', 'SG', ['Ho Chi Minh City']],
                ['Da Nang', 'DN', ['Da Nang']],
                ['Hai Phong', 'HP', ['Hai Phong']],
                ['Khanh Hoa', 'KH', ['Nha Trang']],
                ['Quang Ninh', 'QN', ['Ha Long']],
            ],
            'PH' => [
                ['Metro Manila', '00', ['Manila', 'Makati', 'Quezon City', 'Taguig', 'Pasig', 'Paranaque']],
                ['Cebu', '07', ['Cebu City', 'Lapu-Lapu']],
                ['Davao', '11', ['Davao City']],
                ['Iloilo', '06', ['Iloilo City']],
                ['Laguna', '04', ['Calamba', 'Santa Rosa']],
                ['Batangas', '04', ['Batangas City']],
            ],
            'JP' => [
                ['Tokyo', '13', ['Tokyo', 'Hachioji']],
                ['Osaka', '27', ['Osaka', 'Sakai']],
                ['Kyoto', '26', ['Kyoto']],
                ['Kanagawa', '14', ['Yokohama', 'Kawasaki']],
                ['Aichi', '23', ['Nagoya']],
                ['Hokkaido', '01', ['Sapporo']],
                ['Fukuoka', '40', ['Fukuoka']],
                ['Okinawa', '47', ['Naha']],
            ],
            'KR' => [
                ['Seoul', '11', ['Seoul']],
                ['Busan', '26', ['Busan']],
                ['Incheon', '28', ['Incheon']],
                ['Gyeonggi', '41', ['Suwon', 'Goyang', 'Seongnam']],
                ['Daegu', '27', ['Daegu']],
                ['Jeju', '49', ['Jeju City']],
            ],
            'CN' => [
                ['Beijing', '11', ['Beijing']],
                ['Shanghai', '31', ['Shanghai']],
                ['Guangdong', '44', ['Guangzhou', 'Shenzhen', 'Dongguan', 'Foshan']],
                ['Zhejiang', '33', ['Hangzhou', 'Ningbo']],
                ['Jiangsu', '32', ['Nanjing', 'Suzhou', 'Wuxi']],
                ['Sichuan', '51', ['Chengdu']],
                ['Hubei', '42', ['Wuhan']],
                ['Shaanxi', '61', ['Xi\'an']],
                ['Chongqing', '50', ['Chongqing']],
                ['Fujian', '35', ['Xiamen', 'Fuzhou']],
            ],
            'TW' => [
                ['Taipei', 'TPE', ['Taipei', 'New Taipei']],
                ['Kaohsiung', 'KHH', ['Kaohsiung']],
                ['Taichung', 'TXG', ['Taichung']],
                ['Tainan', 'TNN', ['Tainan']],
            ],
            'RU' => [
                ['Moscow', 'MOW', ['Moscow']],
                ['Saint Petersburg', 'SPE', ['Saint Petersburg']],
                ['Tatarstan', 'TA', ['Kazan']],
                ['Sverdlovsk Oblast', 'SV', ['Yekaterinburg']],
                ['Novosibirsk Oblast', 'NVS', ['Novosibirsk']],
            ],
            'TR' => [
                ['Istanbul', '34', ['Istanbul']],
                ['Ankara', '06', ['Ankara']],
                ['Izmir', '35', ['Izmir']],
                ['Antalya', '07', ['Antalya']],
                ['Bursa', '16', ['Bursa']],
            ],
            'IL' => [
                ['Tel Aviv District', 'TA', ['Tel Aviv', 'Ramat Gan']],
                ['Central District', 'M', ['Rishon LeZion', 'Petah Tikva']],
                ['Jerusalem District', 'JM', ['Jerusalem']],
                ['Haifa District', 'HA', ['Haifa']],
            ],
            'DE' => [
                ['Berlin', 'BE', ['Berlin']],
                ['Bavaria', 'BY', ['Munich', 'Nuremberg', 'Augsburg']],
                ['Hamburg', 'HH', ['Hamburg']],
                ['Hesse', 'HE', ['Frankfurt', 'Wiesbaden']],
                ['North Rhine-Westphalia', 'NW', ['Cologne', 'Dusseldorf', 'Dortmund', 'Essen', 'Bonn']],
                ['Baden-Wurttemberg', 'BW', ['Stuttgart', 'Karlsruhe', 'Freiburg']],
                ['Lower Saxony', 'NI', ['Hanover']],
                ['Saxony', 'SN', ['Leipzig', 'Dresden']],
                ['Bremen', 'HB', ['Bremen']],
                ['Rhineland-Palatinate', 'RP', ['Mainz']],
            ],
            'FR' => [
                ['Île-de-France', 'IDF', ['Paris', 'Versailles', 'Boulogne-Billancourt']],
                ['Provence-Alpes-Côte d\'Azur', 'PAC', ['Marseille', 'Nice', 'Cannes', 'Aix-en-Provence']],
                ['Auvergne-Rhône-Alpes', 'ARA', ['Lyon', 'Grenoble']],
                ['Occitanie', 'OCC', ['Toulouse', 'Montpellier', 'Nîmes']],
                ['Hauts-de-France', 'HDF', ['Lille']],
                ['Grand Est', 'GES', ['Strasbourg', 'Reims']],
                ['Nouvelle-Aquitaine', 'NAQ', ['Bordeaux']],
                ['Brittany', 'BRE', ['Rennes']],
            ],
            'ES' => [
                ['Madrid', 'MD', ['Madrid']],
                ['Catalonia', 'CT', ['Barcelona', 'Girona', 'Tarragona']],
                ['Andalusia', 'AN', ['Seville', 'Malaga', 'Granada', 'Cordoba']],
                ['Valencia', 'VC', ['Valencia', 'Alicante']],
                ['Basque Country', 'PV', ['Bilbao', 'San Sebastian']],
                ['Galicia', 'GA', ['Santiago de Compostela', 'A Coruña']],
                ['Canary Islands', 'CN', ['Las Palmas', 'Santa Cruz de Tenerife']],
                ['Balearic Islands', 'IB', ['Palma']],
            ],
            'IT' => [
                ['Lazio', 'LAZ', ['Rome']],
                ['Lombardy', 'LOM', ['Milan', 'Monza', 'Bergamo']],
                ['Campania', 'CAM', ['Naples', 'Salerno']],
                ['Sicily', 'SIC', ['Palermo', 'Catania', 'Messina']],
                ['Veneto', 'VEN', ['Venice', 'Verona', 'Padua']],
                ['Piedmont', 'PIE', ['Turin']],
                ['Tuscany', 'TUS', ['Florence', 'Pisa', 'Siena']],
                ['Emilia-Romagna', 'EMR', ['Bologna', 'Parma', 'Modena']],
                ['Apulia', 'PUG', ['Bari', 'Lecce']],
            ],
            'NL' => [
                ['North Holland', 'NH', ['Amsterdam', 'Haarlem']],
                ['South Holland', 'ZH', ['Rotterdam', 'The Hague', 'Leiden']],
                ['Utrecht', 'UT', ['Utrecht']],
                ['North Brabant', 'NB', ['Eindhoven', 'Tilburg']],
            ],
            'CH' => [
                ['Zurich', 'ZH', ['Zurich']],
                ['Bern', 'BE', ['Bern']],
                ['Geneva', 'GE', ['Geneva']],
                ['Basel-Stadt', 'BS', ['Basel']],
                ['Vaud', 'VD', ['Lausanne']],
                ['Ticino', 'TI', ['Lugano']],
            ],
            'BE' => [
                ['Brussels', 'BRU', ['Brussels']],
                ['Flanders', 'VLG', ['Antwerp', 'Ghent', 'Bruges', 'Leuven']],
                ['Wallonia', 'WAL', ['Liege', 'Namur', 'Charleroi']],
            ],
            'PT' => [
                ['Lisbon', 'LS', ['Lisbon', 'Cascais', 'Sintra']],
                ['Porto', 'PO', ['Porto', 'Vila Nova de Gaia']],
                ['Faro', 'FA', ['Faro', 'Albufeira']],
                ['Madeira', 'MD', ['Funchal']],
            ],
            'AT' => [
                ['Vienna', 'WI', ['Vienna']],
                ['Upper Austria', 'OA', ['Linz']],
                ['Styria', 'ST', ['Graz']],
                ['Tyrol', 'TL', ['Innsbruck']],
                ['Salzburg', 'SB', ['Salzburg']],
            ],
            'IE' => [
                ['Dublin', 'D', ['Dublin']],
                ['Cork', 'CO', ['Cork']],
                ['Galway', 'G', ['Galway']],
                ['Limerick', 'L', ['Limerick']],
            ],
            'BR' => [
                ['São Paulo', 'SP', ['São Paulo', 'Campinas', 'Santos', 'Guarulhos']],
                ['Rio de Janeiro', 'RJ', ['Rio de Janeiro', 'Niterói']],
                ['Minas Gerais', 'MG', ['Belo Horizonte', 'Uberlândia']],
                ['Distrito Federal', 'DF', ['Brasília']],
                ['Bahia', 'BA', ['Salvador']],
                ['Paraná', 'PR', ['Curitiba']],
                ['Rio Grande do Sul', 'RS', ['Porto Alegre']],
                ['Ceará', 'CE', ['Fortaleza']],
            ],
            'MX' => [
                ['Mexico City', 'CMX', ['Mexico City']],
                ['Jalisco', 'JAL', ['Guadalajara', 'Puerto Vallarta']],
                ['Nuevo León', 'NLE', ['Monterrey']],
                ['Baja California', 'BCN', ['Tijuana', 'Mexicali']],
                ['Quintana Roo', 'ROO', ['Cancún', 'Playa del Carmen']],
                ['Puebla', 'PUE', ['Puebla']],
            ],
            'AR' => [
                ['Buenos Aires', 'B', ['Buenos Aires']],
                ['Buenos Aires Province', 'BA', ['La Plata', 'Mar del Plata']],
                ['Córdoba', 'X', ['Córdoba']],
                ['Santa Fe', 'S', ['Rosario', 'Santa Fe']],
                ['Mendoza', 'MZ', ['Mendoza']],
            ],
            'CL' => [
                ['Santiago Metropolitan', 'RM', ['Santiago']],
                ['Valparaíso', 'VS', ['Valparaíso', 'Viña del Mar']],
                ['Biobío', 'BI', ['Concepción']],
                ['Araucanía', 'AR', ['Temuco']],
            ],
            'CO' => [
                ['Bogotá', 'BOG', ['Bogotá']],
                ['Antioquia', 'ANT', ['Medellín']],
                ['Valle del Cauca', 'VAC', ['Cali']],
                ['Atlántico', 'ATL', ['Barranquilla']],
            ],
            'PE' => [
                ['Lima', 'LIM', ['Lima', 'Callao']],
                ['Arequipa', 'ARE', ['Arequipa']],
                ['Cusco', 'CUS', ['Cusco']],
                ['La Libertad', 'LAL', ['Trujillo']],
            ],
            'EG' => [
                ['Cairo', 'C', ['Cairo']],
                ['Giza', 'GZ', ['Giza', 'Hurghada']],
                ['Alexandria', 'ALX', ['Alexandria']],
                ['South Sinai', 'JS', ['Sharm El Sheikh']],
            ],
            'ZA' => [
                ['Gauteng', 'GP', ['Johannesburg', 'Pretoria', 'Soweto']],
                ['Western Cape', 'WC', ['Cape Town', 'Stellenbosch']],
                ['KwaZulu-Natal', 'KZN', ['Durban', 'Pietermaritzburg']],
                ['Eastern Cape', 'EC', ['Gqeberha', 'East London']],
                ['Free State', 'FS', ['Bloemfontein']],
            ],
            'NG' => [
                ['Lagos', 'LA', ['Lagos', 'Ikeja']],
                ['Federal Capital Territory', 'FC', ['Abuja']],
                ['Rivers', 'RI', ['Port Harcourt']],
                ['Oyo', 'OY', ['Ibadan']],
                ['Kano', 'KN', ['Kano']],
                ['Kaduna', 'KD', ['Kaduna']],
                ['Anambra', 'AN', ['Onitsha', 'Awka']],
            ],
            'KE' => [
                ['Nairobi', '30', ['Nairobi']],
                ['Mombasa', '37', ['Mombasa']],
                ['Kisumu', '35', ['Kisumu']],
                ['Nakuru', '32', ['Nakuru']],
            ],
            'MA' => [
                ['Casablanca-Settat', '06', ['Casablanca', 'Mohammedia']],
                ['Rabat-Salé-Kénitra', '04', ['Rabat', 'Sale']],
                ['Marrakech-Safi', '07', ['Marrakech']],
                ['Fès-Meknès', '05', ['Fès', 'Meknès']],
                ['Tangier-Tétouan-Al Hoceima', '01', ['Tangier']],
                ['Souss-Massa', '08', ['Agadir']],
            ],
            'NZ' => [
                ['Auckland', 'AUK', ['Auckland']],
                ['Wellington', 'WGN', ['Wellington', 'Lower Hutt']],
                ['Canterbury', 'CAN', ['Christchurch']],
                ['Otago', 'OTA', ['Dunedin', 'Queenstown']],
                ['Waikato', 'WKO', ['Hamilton']],
            ],
            'SG' => [['Singapore', 'SG', ['Singapore']]],
            'HK' => [['Hong Kong', 'HK', ['Hong Kong']]],
            'MO' => [['Macau', 'MO', ['Macau']]],
            'QA' => [['Qatar', 'QA', ['Doha', 'Al Rayyan']]],
            'KW' => [['Kuwait', 'KU', ['Kuwait City']]],
            'BH' => [['Bahrain', 'BH', ['Manama', 'Muharraq']]],
            'MV' => [['Maldives', 'MV', ['Male']]],
            'MC' => [['Monaco', 'MC', ['Monaco']]],
            'VA' => [['Vatican City', 'VA', ['Vatican City']]],
            'SM' => [['San Marino', 'SM', ['San Marino']]],
            'AD' => [['Andorra', 'AD', ['Andorra la Vella']]],
            'LI' => [['Liechtenstein', 'LI', ['Vaduz']]],
            'MT' => [['Malta', 'MT', ['Valletta', 'Sliema']]],
            'LU' => [['Luxembourg', 'LU', ['Luxembourg', 'Esch-sur-Alzette']]],
            'BN' => [['Brunei', 'BN', ['Bandar Seri Begawan']]],
            'CY' => [['Cyprus', 'CY', ['Nicosia', 'Limassol', 'Larnaca']]],
            'IS' => [['Iceland', 'IS', ['Reykjavik']]],
            'EE' => [['Estonia', 'EE', ['Tallinn', 'Tartu']]],
            'LV' => [['Latvia', 'LV', ['Riga']]],
            'LT' => [['Lithuania', 'LT', ['Vilnius', 'Kaunas']]],
            'PL' => [['Poland', 'PL', ['Warsaw', 'Krakow', 'Gdansk', 'Wroclaw', 'Poznan']]],
            'SE' => [['Sweden', 'SE', ['Stockholm', 'Gothenburg', 'Malmö']]],
            'NO' => [['Norway', 'NO', ['Oslo', 'Bergen', 'Trondheim']]],
            'DK' => [['Denmark', 'DK', ['Copenhagen', 'Aarhus', 'Odense']]],
            'FI' => [['Finland', 'FI', ['Helsinki', 'Tampere']]],
            'GR' => [['Greece', 'GR', ['Athens', 'Thessaloniki', 'Heraklion']]],
            'HU' => [['Hungary', 'HU', ['Budapest', 'Debrecen']]],
            'CZ' => [['Czech Republic', 'CZ', ['Prague', 'Brno']]],
            'RO' => [['Romania', 'RO', ['Bucharest', 'Cluj-Napoca', 'Timisoara']]],
            'UA' => [['Ukraine', 'UA', ['Kyiv', 'Lviv', 'Odesa', 'Kharkiv']]],
        ];

        foreach ($locations as $iso2 => $stateRows) {
            $countryId = $countryIds[$iso2] ?? null;
            if (! $countryId) {
                continue;
            }

            foreach ($stateRows as [$stateName, $stateCode, $cityNames]) {
                $state = State::updateOrCreate(
                    ['country_id' => $countryId, 'name' => $stateName],
                    ['state_code' => $stateCode, 'status' => true]
                );

                foreach ($cityNames as $cityName) {
                    City::updateOrCreate(
                        ['country_id' => $countryId, 'state_id' => $state->id, 'name' => $cityName],
                        ['status' => true]
                    );
                }
            }
        }
    }
}