import {
    LayoutDashboard, ShoppingCart, FolderKanban, Briefcase, Tag,
    Users, UserCheck, ShieldCheck, KeyRound, Sliders, Menu as MenuIcon,
    Boxes, MonitorSmartphone, AlertTriangle, Megaphone, Globe,
    MessageSquareText, FileText, Handshake, PlayCircle, Settings2,
    Mail, CreditCard, Banknote, Wallet, Star, Settings, Bell,
    LifeBuoy, History, Power, Clock, BadgeCheck, TrendingUp,
    Home, Search, Calendar, BarChart3, PieChart, Download,
    Upload, RefreshCw, Trash2, Edit2, Plus, Eye, EyeOff,
    Lock, Unlock, Smartphone, Laptop, Tablet, Monitor,
    ChevronDown, ChevronRight, ChevronLeft, ArrowLeft,
    ArrowRight, ExternalLink, Link, Unlink, Copy, Scissors,
    Save, Send, Share2, Printer, Maximize2, Minimize2,
    Filter, SortAsc, SortDesc, MoreVertical, MoreHorizontal,
    CheckCircle, XCircle, AlertCircle, Info, HelpCircle,
    Zap, Flame, Target, Award, Gift, Package, Truck,
    MapPin, Navigation, Compass, Radar, Shield, ShieldAlert,
    ShieldCheck as ShieldCheckIcon, Fingerprint, Scan,
    Database, Server, Cloud, HardDrive, Cpu, MemoryStick,
    Wifi, Bluetooth, Signal, Radio, Tv, Camera, Video,
    Image, Music, Headphones, Mic, Volume2, VolumeX,
    BookOpen, Book, Bookmark, Library, Archive, Folder,
    FolderOpen, File, FileText as FileTextIcon, FilePlus,
    FileMinus, FileSearch, Paperclip, Clipboard, ClipboardList,
    CheckSquare, Square, Circle, Triangle, Hexagon, Octagon,
    Hash, AtSign, Percent, DollarSign,
    Thermometer, Droplets, Wind, Sun, Moon, CloudRain,
    CloudSnow, CloudLightning, Rainbow, Umbrella,
} from 'lucide-react';

const iconMap = {
    dashboard: LayoutDashboard, 'layout-dashboard': LayoutDashboard,
    orders: ShoppingCart, 'shopping-cart': ShoppingCart,
    projects: FolderKanban, 'folder-kanban': FolderKanban,
    services: Briefcase, briefcase: Briefcase,
    categories: Tag, tag: Tag,
    buyers: Users, users: Users,
    sellers: UserCheck, 'user-check': UserCheck,
    roles: ShieldCheck, 'shield-check': ShieldCheck,
    permissions: KeyRound, 'key-round': KeyRound,
    menus: MenuIcon, menu: MenuIcon, 'menu-icon': MenuIcon,
    settings: Sliders, sliders: Sliders,
    devices: MonitorSmartphone, 'monitor-smartphone': MonitorSmartphone,
    suspicious: AlertTriangle, 'alert-triangle': AlertTriangle,
    banners: Megaphone, megaphone: Megaphone,
    homepage: Globe, globe: Globe, website: Globe,
    faqs: MessageSquareText, 'message-square-text': MessageSquareText,
    testimonials: FileText, 'file-text': FileText,
    tutorials: PlayCircle, 'play-circle': PlayCircle,
    'brand-partners': Handshake, handshake: Handshake,
    'team-members': Users, 'user-check': UserCheck, 'users': Users,
    invoices: FileText, 'invoice-designs': FileText,
    'email-settings': Mail, mail: Mail,
    'payment-gateways': CreditCard, 'credit-card': CreditCard,
    settlements: Banknote, banknote: Banknote,
    wallet: Wallet, star: Star, reviews: Star,
    'app-builds': Smartphone, 'install-app': Download,
    notifications: Bell, bell: Bell,
    support: LifeBuoy, 'life-buoy': LifeBuoy,
    'login-history': History, history: History,
    seo: Globe, maintenance: Sliders,
    'invoice-settings': Settings2, 'settings-2': Settings2,
    home: Home, search: Search, calendar: Calendar,
    'bar-chart': BarChart3, 'pie-chart': PieChart,
    download: Download, upload: Upload, refresh: RefreshCw,
    trash: Trash2, edit: Edit2, plus: Plus,
    eye: Eye, 'eye-off': EyeOff,
    lock: Lock, unlock: Unlock,
    smartphone: Smartphone, laptop: Laptop, tablet: Tablet, monitor: Monitor,
    power: Power, clock: Clock, 'badge-check': BadgeCheck,
    'trending-up': TrendingUp, boxes: Boxes,
};

export default iconMap;
